### ISSUE TITLE
KM 標題的樣式跑掉

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/MerMer-official#166]
<img width="1437" alt="image" src="https://github.com/CAFECA-IO/MerMer-official/assets/114177573/9c41c819-f562-4826-b9a2-6c2b4c04c07a">

`<h1>` 等 css 樣式不見了，需調查原因

**Comment by TinyMurky** [comment]
took 1 hours
done

修正成果
![Screenshot 2024-03-05 at 12-00-43 帛琉數位居住計畫](https://github.com/CAFECA-IO/MerMer-official/assets/55581222/705ac779-e260-402a-a7db-23bd1be2fc28)
