### ISSUE TITLE
[Bug] always use https protocol in getServerSideProps

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/MerMer-official#168]
-  x-forwarded-proto will be `http,https` after Cloudflare routing
- always use https
- effect with 
  - src/pages/knowledge-management/index.tsx
  - src/pages/knowledge-management/[kmId].tsx
  - src/pages/knowledge-management/author/[authorId].tsx 
  - src/pages/admin/edit/[kmId].tsx
  - src/pages/admin/browse/index.tsx

**Comment by TinyMurky** [comment]
took 1 hours
done
