### ISSUE TITLE
新增  Ethereum Sharding KM 至官網

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/MerMer-official#177]
- 使用官網提供的KM編輯器功能新增KM

**Comment by TzuHanLiang** [comment]
- take 1.5hr
- 無法更新圖片花了預料之外的時間，最後還是沒有更新成功，已向 @TinyMurky 提及此問題
- 要更新的圖片如下：
![ethereum_sharding](https://github.com/CAFECA-IO/MerMer-official/assets/17249354/9c57ab7a-30db-45be-b597-3d5df4d3f19d)
- KM的位置：https://mermer.com.tw/en/knowledge-management/20240327001

**Comment by TinyMurky** [comment]
目前先手動上傳
![圖片](https://github.com/CAFECA-IO/MerMer-official/assets/55581222/eb31322a-814b-4b15-93f8-2fcb7300e6b9)

並於以下pull request中進行修復
- [ ]  #178
